USE [LvivInBooks_OLTP]
GO

/****** Object:  Table [dbo].[GENRES_BOOKS]    Script Date: 03.12.2023 16:02:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[GENRES_BOOKS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[GRef] [int] NULL,
	[BRef] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[GENRES_BOOKS]  WITH CHECK ADD FOREIGN KEY([BRef])
REFERENCES [dbo].[BOOKS] ([ID])
GO

ALTER TABLE [dbo].[GENRES_BOOKS]  WITH CHECK ADD FOREIGN KEY([GRef])
REFERENCES [dbo].[GENRES] ([ID])
GO

